apply plugin: 'java'

def cltJavaVersion = project.findProperty('clt_java_version')?.toString()?.trim()
if (!cltJavaVersion) {
    cltJavaVersion = project.hasProperty('neo_version') ? '21' : '17'
}
def cltJavaLanguageVersion = JavaLanguageVersion.of(Integer.parseInt(cltJavaVersion))

java.toolchain.languageVersion = cltJavaLanguageVersion

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))
java.withSourcesJar()
java.withJavadocJar()

jar {
    manifest {
        attributes([
                'Specification-Title'     : mod_name,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : project.jar.archiveVersion,
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'Timestamp'               : System.currentTimeMillis(),
                'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                'Built-On-Minecraft'      : minecraft_version
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = cltJavaLanguageVersion.asInt()
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

javadoc {
    options.addStringOption('Xdoclint:none', '-quiet')
}

tasks.named('compileJava').configure {
    options.compilerArgs = ['-Xdiags:verbose']
}
